---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure epel-release is installed prior to installing host packages
  yum:
    pkg: epel-release
    state: present
  tags:
    - openstack-yum-packages
    - openstack-packages

- name: Download RDO repository RPM
  get_url:
    url: https://rdoproject.org/repos/openstack-ocata/rdo-release-ocata.rpm
    dest: /tmp/rdo-release-ocata.rpm
  tags:
    - openstack-yum-packages
    - openstack-packages

- name: Install EPEL, RDO, and yum priorities plugin
  yum:
    name: "{{ item }}"
    state: "{{ openstack_hosts_package_state }}"
  with_items:
    - epel-release
    - yum-plugin-priorities
    - /tmp/rdo-release-ocata.rpm
  tags:
    - openstack-yum-packages
    - openstack-packages

- name: Increase RDO priority to 50
  command: >
    yum-config-manager
      --enable openstack-ocata
      --setopt="openstack-ocata.priority=50"
      --enable rdo-qemu-ev
      --setopt="rdo-qemu-ev.priority=50"
  tags:
    - openstack-yum-packages
    - openstack-packages

- name: Install host packages
  yum:
    pkg: "{{ item }}"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ openstack_host_distro_packages }}"
  tags:
    - openstack-yum-packages
    - openstack-packages

- name: Disable requiretty for root sudo on centos
  template:
    dest: /etc/sudoers.d/openstack-ansible
    owner: root
    group: root
    mode: "0440"
    src: sudoers.j2
  when:
    - ansible_pkg_mgr == 'yum'
